[package]
name = "wfx-utils"
version = "0.0.1"
edition = "2024"
description = "Utilities for the wfx game engine"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/orgrinrt/wfx"
homepage = "https://github.com/orgrinrt/wfx"
authors = ["orgrinrt <orgrinrt@ikiuni.dev>", "Hiisi Digital Oy <hey@hiisi.digital>"]
rust-version = "1.87.0"
keywords = ["utils", "wfx"]

[lib]
crate-type = ["cdylib"]

[dependencies]
log.workspace = true # the workspace version has some specific features set for slight optimisations
