[unstable]
codegen-backend = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    # NOTE: requires manual installation of lld
    "-Clink-arg=-fuse-ld=lld",
     "-Zshare-generics=y",
     "-Zthreads=0",
]
rustdocflags = [
    # NOTE: requires manual installation of lld
    "-Clink-arg=-fuse-ld=lld",
]

[target.x86_64-apple-darwin]
rustflags = [
    # NOTE: might require manual installation of llvm
#     "-Clink-arg=-fuse-ld=/usr/local/opt/llvm/bin/ld64.lld",

     "-Zshare-generics=y",
     "-Zthreads=0",
]

[target.aarch64-apple-darwin]
rustflags = [
    # NOTE: might require manual installation of llvm
#     "-Clink-arg=-fuse-ld=/opt/homebrew/opt/llvm/bin/ld64.lld",

     "-Zshare-generics=y",
     "-Zthreads=0",
]

[target.x86_64-pc-windows-msvc]
# ```
# cargo install -f cargo-binutils
# rustup component add llvm-tools
# ```
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]
rustflags = [
#     "-Zshare-generics=n", # NOTE: This needs to be off for dyn linking on windows to work
     "-Zthreads=0",
]

# NOTE: this is a workaround for macos compile times for now, might be able to remove down the line
[profile.dev.target.x86_64-apple-darwin]
debug = 1
[profile.dev.target.aarch64-apple-darwin]
debug = 1
